### ISSUE TITLE
54 key (or more version)

### ISSUE THREAD

**Issue by BorjaLL** [zzeneg/stront#1]
This looks amazing! I'd love a version with more keys for my use cases. How hard would that be to iterate ?

**Comment by zzeneg** [comment]
So the main problem is the number of IO pins on the MCU, I'm already using all of them - the LCD display requires quite a lot. For 54+ keys we'd need 2-3 extra pins, and I think the optimal solution would be to replace the MCU with something bigger, in the form factor of original Pi Pico, for example Waveshare RP2040 Plus. It has 6 more IO pins which is more than enough, it's much bigger but given the extra row it should be ok. The total cost will increase but not by much.
Of course these changes will require complete rework of the keyboard and unfortunately I'm not interested in so many keys, so I would not create such version by myself. But I welcome any attempt to fork Stront and create a bigger version (or just make it as a new keyboard).

**Comment by Zilvertail** [comment]
Couldn't you drop the rotary encoders and get more keys that way? Then map the rotary functions onto the trackpad perhaps?

**Comment by zzeneg** [comment]
Yes, it's a valid alternative, you can drop them and get 30 keys per side. Not sure about using trackpad as a replacement, probably it's possible but will need a lot code.
I considered this, but I thought that given the there will be an additional row, you can just put a bigger MCU anyway.

**Comment by Zilvertail** [comment]
Yeah, my point was to get more STRONT's out into the wild without limiting to many people, i really like the qmk-hid-host you wrote to handle the keyboard, and would love for more to adopt that, and getting more keys easily onto the STRONT would help develop the chances of a broader adaptation :)

**Comment by zzeneg** [comment]
So if anyone looks for an open-sources 54-key alternative with display and touchpad I'd recommend Dilemma MAX (4x6+3) offered by @Bastardkb - https://github.com/Bastardkb/Dilemma

**Comment by zzeneg** [comment]
So if anyone looks for an open-sources 54-key alternative with display and touchpad I'd recommend Dilemma MAX (4x6+3) offered by @Bastardkb - https://github.com/Bastardkb/Dilemma. There is no build guide or case for the displays at the moment but the PCB itself supports it.
