### ISSUE TITLE
Updated PCBWay link?

### ISSUE THREAD

**Issue by Ramblurr** [zzeneg/stront#2]
Hey there! I want to build this lovely keyboard, but I noticed that the PCBWay link:

1. Is Choc only
2. Was last updated in April

It would be great to get updated versions of the Choc and MX pcbs so you get some kickback when I print it!

**Comment by zzeneg** [comment]
Hey, thank you for reminding me :) I did not work on Choc version since April, but I uploaded STL files and created a separate project for MX/KS-33 https://www.pcbway.com/project/shareproject/Stront_MX_KS_33_keyboard_6a70e49a.html
