### ISSUE TITLE
Breakout the reset button

### ISSUE THREAD

**Issue by CardboardMechanic** [zzeneg/stront#5]
Now that the case is all screwed on I want to update my firmware and try out different configurations, but the reset button is not accessible. I'd love to see a rev of the board and case that breaks out the reset button so I can flash new firmware without taking the case off.

**Comment by zzeneg** [comment]
It's not possible to breakout reset button on RP2040 Zero, unfortunately. Use bootloader key in keymap + bootmagic, default firmware has them.

**Comment by CardboardMechanic** [comment]
Nice, that's what I needed 👍
