### ISSUE TITLE
Default keymap has P mapped incorrectly.

### ISSUE THREAD

**Issue by JustinPack** [zzeneg/stront#6]
P seems to be swapped with ; on the default keymap.

**Comment by zzeneg** [comment]
So my personalized `zzeneg` keymaps have them swapped, that's how I use it.
Other keymaps should have ; in a regular place - and that's what I see in code. The only place it was swapped is the layout drawing in the comments, so I fixed that. However I may have mixed some layouts/names/files so I regenerated all firmware files with all permutations, I wanted to do it anyway. I hope everything is fine now.
