### ISSUE TITLE
stront40 firmware

### ISSUE THREAD

**Issue by tangbonze** [zzeneg/stront#7]
Hi There:
First I want to say Thank you for create stront. It is really amazing. 
I notice you have create new stront40. I can't wait to try it. 
May I ask do you have plan to release firmware or it just same as stront?
Thanks.

**Comment by zzeneg** [comment]
Hey! Thanks for following my work :) stront40 is work in progress, I created and ordered it but did not assemble and test it yet. There's no firmware, it will be just a bit different from regular stront.
I should be able to properly test PCB and firmware in a week or two but the case will take longer.
After I test it, I'll merge it to main branch.

**Comment by tangbonze** [comment]
thank you. I will wait for your release.
