### ISSUE TITLE
Clipboard plugin

### ISSUE THREAD

**Issue by RicardoTM05** [zzeneg/stront#8]
Hey zzeneg, sorry for creating this issue here, but you deleted the original PluginClipboard github. I know [that plugin for rainmeter](url=https://forum.rainmeter.net/viewtopic.php?t=20995) is too old, but I was wondering if you could add something to it, since I'm still using it.

The problem is that I'm using it on a color selector I made which I use a lot on Illustrator. I use the plugin to paste colors to it. The problem is when I copy a big shape my pc lags a lot, because sgv codes can be 300k characters long.. so I would love it if it could actually recognize this stuff and ignore it. Also if you could add some sort of option to only copy text and not files nor images. Like a TextOnly=1 option and same for images and files. Some way to let the plugin know what to actually copy and what to ignore.

Again, I apologize for posting this here. Have a good day.

**Comment by zzeneg** [comment]
Wow, that was a long time ago :) Unfortunately it looks like I actually deleted that repo when I stopped using Rainmeter, and I don't have sources for that plugin anymore. I also don't see much sense in that plugin really, Windows has native clipboard history since Windows 10, which works much better.

**Comment by RicardoTM05** [comment]
That's true, long long ago.

That's too bad, my only hope now is that someone else creates another one.. Or that I learn all the stuff to make one since I have no idea lol. 

It makes sense in Rainmeter's environment. Rainmeter needs a measure to know what's in the clipboard in order to use it on actions or anything else. In my case, speed is important, so I use it in my color selector to be able to paste the colors by simply clicking on a swatch, instead of needing a text box and me pressing ctrl + v. I also use it on a search bar, which just saves me from having to press win+v, click something, then pressing ctrl + v. Instead I only need to click the item I want directly.

Anyway, I started a [topic ](https://forum.rainmeter.net/viewtopic.php?t=43968) in the Rainmeter forum to see if anyone is interested in remaking it, although they sent me to your github lol. So there's not much hope for me.

Thank you anyway, have a great day :)
